version: "3"
services:
  rosbag_analysis:
    image: shreyasmanjunath/rosbag_analysis
    environment:
      ROSBAG_NAME: ${ROSBAG_NAME}
      BAG_LOCATION: ${BAG_LOCATION}
      OUTPUT_LOCATION: ${OUTPUT_LOCATION}
    command:
      - /bin/bash
      - -ecx
      - |
          roslaunch rosbag_analysis_task analyse.launch rosbag_file_name:=/ros_ws/src/rosbag_analysis_task/bag/${ROSBAG_NAME}
    volumes:
      - ${BAG_LOCATION}:/ros_ws/src/rosbag_analysis_task/bag 
      - ${OUTPUT_LOCATION}:/ros_ws/src/rosbag_analysis_task/data
